title: Kiwiki
description: "Web Kiwi Virus Wiki"
theme: just-the-docs
baseurl: "/kiwiki"

color_scheme: light

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

exclude:
  - config/
  - data/
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - content/viruses/_template.md

search_enabled: false
heading_anchor: true
heading_anchor_style: github
nav_sort: case_insensitive

# No footer
footer_content: ""

# No back to top
back_to_top: false

# Disable nav sidebar
nav_enabled: false

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
